import { AlertTriangle } from "lucide-react";
import { formatDate } from "@/lib/utils/formatting";

interface DisclaimerProps {
  generatedAt?: string;
}

export function Disclaimer({ generatedAt }: DisclaimerProps) {
  return (
    <div className="rounded-lg border border-yellow-200 dark:border-yellow-900/30 bg-yellow-50 dark:bg-yellow-950/20 px-4 py-3 mt-6">
      <div className="flex gap-2.5">
        <AlertTriangle className="h-4 w-4 text-yellow-600 dark:text-yellow-400 shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-xs font-semibold text-yellow-800 dark:text-yellow-300">
            Investment Disclaimer
          </p>
          <p className="text-xs text-yellow-700 dark:text-yellow-400 leading-relaxed">
            This report is generated by AI for informational purposes only. It does not constitute
            investment advice, a recommendation, or a solicitation to buy or sell any securities.
            StockMind AI makes no warranties about the accuracy or completeness of this information.
            Past performance is not indicative of future results. Always conduct your own research
            and consult a qualified financial advisor before making investment decisions.
          </p>
          {generatedAt && (
            <p className="text-xs text-yellow-600 dark:text-yellow-500">
              Generated: {formatDate(generatedAt)} · Powered by StockMind AI
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
