import { AlertTriangle } from "lucide-react";
import { formatDate } from "@/lib/utils/formatting";

interface DisclaimerProps {
  generatedAt?: string;
}

export function Disclaimer({ generatedAt }: DisclaimerProps) {
  return (
    <div className="rounded-lg border border-border bg-muted/30 p-4 mt-6">
      <div className="flex items-start gap-2">
        <AlertTriangle className="h-4 w-4 text-warning shrink-0 mt-0.5" />
        <div className="space-y-1">
          <p className="text-xs font-semibold text-foreground">Investment Disclaimer</p>
          <p className="text-xs text-muted-foreground leading-relaxed">
            This report is generated by AI for informational purposes only. It does not constitute
            investment advice, a recommendation, or a solicitation to buy or sell any securities.
            StockMind AI makes no warranties about the accuracy or completeness of this information.
            Past performance is not indicative of future results. Always conduct your own research
            and consult a qualified financial advisor before making investment decisions.
          </p>
          {generatedAt && (
            <p className="text-xs text-muted-foreground/70">
              Generated: {formatDate(generatedAt)} &middot; Powered by StockMind AI
            </p>
          )}
        </div>
      </div>
    </div>
  );
}
